### ISSUE TITLE
options.stopOnError is overwritten in constructor 

### ISSUE THREAD

**Issue by dutu** [zoellner/watchpuppy#2]
It looks that `options.stopOnError` is overwritten in constructor and always set to `true`.

https://github.com/zoellner/watchpuppy/blob/c3ad16422964077c90b398f3b559268d121b0ea5/index.js#L21

should be 
```js
this.stopOnError = options.hasOwnProperty(`stopOnError`) ? options.stopOnError : true
```

**Comment by zoellner** [comment]
you're right. want to make it a PR? otherwise I'll probably get to it next week to fix
